const dataDummy= [
    {
        id: 1,
        heading: "Janhvi Kapoor keeps it simple in blue lehenga, Bhumi Pednekar turns ‘golden queen’ at India Couture Week 2023",
        image: 'https://www.hindustantimes.com/ht-img/img/2023/07/28/550x309/janhvi_kapoor_bhumi_pednekar_ramp_1690524861909_1690526171812.jpg',
        description: "Actors Janhvi Kapoor and Bhumi Pednekar walked the ramp at the India Couture Week 2023 on Thursday. While Janhvi wore a shimmery blue lehenga, Bhumi was in a golden gown with a thigh-high slit.",
        category: "Bollywood",
    },
    {
        id: 2,
        heading: "Rocky Aur Rani Kii Prem Kahaani box office collection Day 1: Karan Johar’s film earns less than Oppenheimer on opening day, makes Rs 11.5 crore",
        image: "https://images.indianexpress.com/2023/07/rocky-rani-1.jpg?w=640",
        description: "Rocky Aur Rani Kii Prem Kahaani box office collection Day 1: Karan Johar's Rocky Aur Rani Kii Prem Kahaani, starring Alia Bhatt and Ranveer Singh in the lead roles, earned a whopping Rs 11.5 crore from Indian theatres on its first day.",
        category: "Bollywood",
    },
    {
        id: 3,
        heading: "Bawaal Trailer Review: Varun-Janhvi’s Chaotic Love-Saga About Hitler Narrates The Battle Within, Watch",
        image: "https://static.india.com/wp-content/uploads/2023/07/bawaal-trailer-varun-janhvi-world-war-hitler.jpeg",
        description: "Varun Dhawan and Janhvi Kapoor’s much-awaited trailer of their love story Bawaal released on Sunday, July 9, 2023. Varun and Janhvi are sharing screen space together for the first time in the Nitesh Tiwari directorial. The filmmaker known for movies like Dangal and Chhichhore is known for films about hope and motivation. The teaser showcased small-town romance between a girl-next-door and a boy full of swagger portrayed by Varun and Janhvi respectively. The teaser ended with visuals of holocaust which generated a lot of curiosity among cinephiles. Netizens were concerned about how the world’s most sensitive topic has been executed in a modern-day love story.",
        category: "Bollywood",
    },

    {
        id: 4,
        heading: " Janhvi Kapoor As Desi Mermaid Stuns In Electric Blue Lehenga With Sexy Bralette And Cape, See Pics",
        image: "https://static.india.com/wp-content/uploads/2023/07/Janhvi-Kapoor-ICW.jpg",
        description: "The Fashion Design Council of India (FDCI) organized India Couture Week began on July 26, 2023.  The biggest designers displayed their collections on the third day of the event, which was nothing short of grandeur and magnificence. Gaurav Gupta’s ‘Hiranyagarbha’ collection grabbed the stage after Varun Bahl’s entrancing wedding couture. Janhvi Kapoor made her runway debut in the designer’s breathtaking ensemble. She created magic in the glamourous electric blue ensemble. She dropped her photos and videos on her social media and captioned them with a blue-coloured heart.",
        category: "Bollywood",
    },
    {
        id: 5,
        heading: "The Story Of Hema Malini’s Wedding With Jeetendra And How Dharmendra Did The Most Filmy Thing To Stop It",
        image: "https://static.india.com/wp-content/uploads/2023/07/The-Story-of-Hema-Malinis-Wedding-to-Jeetendra-And-How-Dharmendra-Did-The-Most-Filmy-Thing-to-Stop-it.jpg",
        description: "Hema Malini has spoken about her professional and personal lives in an interview that is going viral on the internet. The veteran actor has also mentioned how she doesn’t believe in holding grudges while talking about Jeetendra and Sanjeev Kumar whom she had dated in the past. Hema got married to Dharmendra in 1980 but her love story had a lot of ups and downs. One of them was her relationship history with Jeetendra who was really fond of her.",
        category: "Bollywood",
    },
    {
        id: 6,
        heading: "Kartik Aaryan aka Sattu now turns Chandu Champion for Kabir Khan's next, locks Eid 2024 release date",
        image: "https://st1.bollywoodlife.com/wp-content/uploads/2023/07/Feature-image-6.jpg?impolicy=Medium_Widthonly&w=1280&h=900",
        description: "Bringing a large canvas film for the audience, The three powerhouses of the industry, ace Producer Sajid Nadiadwala, prolific director Kabir Khan, and superstar Kartik Aaryan, to bring a massive entertainer on the occasion of Eid al-Adha and are planning to rejoice the festival in June 2024 with yet another titled 'Chandu Champion' a film based on the extraordinary real-life story of not giving up. The trio has kept the excitement of the audience on the edge with the announcement earlier. The massive-scale canvas film will be released on Eid al-Adha 2024 and will set to take Kartik on a new league.All set to treat the audience with a larger canvas film of the next year, the producer-actor, and director trio, Sajid Nadiadwala, Kartik Aaryan, and Kabir Khan will be coming together to bring a massive entertainer on large-scale production based on the extraordinary real-life story of a sportsman and his spirit of never giving up. With the film, the audience will see Kartik doing a film based on a real-life story in which he will portray the character of lead Chandu. As this mega project will bring Sajid and Kabir to come together once again, The film will also mark Kartik and Kabir's first association. As the audience was already excited about the film from the time of its announcement, the title announcement is indeed yet another treat to relish for the fans.",
        category: "Bollywood",
    },
    {
        id: 7,
        heading: "Tiger 3: ‘The Dark Knight’ stunt professional roped in for Salman Khan’s film?",
        image: "https://www.bollywood.com/wp-content/uploads/2022/05/tiger3new1banner.jpg.webp",
        description: " Superstar Salman Khan’s ‘Tiger 3’ is being made on a grand level.As per a source, one of the top stunt professionals from Hollywood, Richard Burden, has been roped in for the film.“Tiger 3 has the biggest heavyweights to craft action sequences. So, you can expect edge-of-the-seat action that will blow your mind. It is a theatrical film with an unmatched scale that will appeal to everyone who loves Hindi cinema,” the source said.Richard has previously worked in top Hollywood films like ‘Batman v Superman: Dawn of Justice’, Christopher Nolan’s ‘The Dark Knight’, Martin Scorsese’s ‘Killers of the Flower Moon’ starring Leonardo Di Caprio and the Brad Pitt starrer action entertainer ‘Bullet Train’.Reportedly, Shah Rukh Khan has a cameo in the film. The official announcement is awaited. Prior to ‘Tiger 3’, Salman and SRK were seen together in Siddharth Anand’s blockbuster ‘Pathaan’. The film, which went on to become a blockbuster, marked the return of SRK to the silver screen after a four-year hiatus.Tiger 3, the third part of the Tiger franchise, is being directed by Maneesh Sharma. The film will release in Hindi, Tamil and Telugu this Diwali. The upcoming actioner stars Emraan Hashmi as the antagonist. Katrina Kaif is also a part of the film. ",
        category: "Bollywood",
    },
    {
        id: 8,
        heading: "Sonam Kapoor invited for UK PM Rishi Sunak’s reception to mark UK-India week",
        image: "https://www.bollywood.com/wp-content/uploads/2023/06/sonamkapoornew3banner.jpg.webp",
        description: "Actor Sonam Kapoor has been invited by the Prime Minister of the United Kingdom, Rishi Sunak to a special reception to celebrate UK-India week 2023, as per a source.The reception will be hosted by Rishi at his official residence and office in 10 Downing Street, and is a part of India Global Forum’s flagship event UK-India week, which is being held from June 26-30 in London.Sonam will be attending the reception on June 28th to represent India and its cultural influence globally.UK-India Week 2023 is the 5th iteration of IGF’s flagship event, a weeklong programme that seeks to honour and strengthen the longstanding partnership between these two countries by providing a platform to spotlight crucial topics.  ",
        category: "Bollywood",
    },
    {
        id: 9,
        heading: "Dream Girl 2: Ananya Panday's Look As Ayushmann Khurrana's Pari Unveiled, Film Teaser To Be Dropped Today",
        image: "https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/31/1252532-dream-girl-2-ananya-panday.jpg",
        description: "Makers of the upcoming comedy film ‘Dream Girl 2’ on Monday unveiled a new poster of their film. Taking to Instagram, actor Ayushmann Khurrana shared the poster and wrote, “Yeh hai Pari, meri Dream Girl! #DreamGirl2Trailer Out Tomorrow! #25AugustHogaMast #DreamGirl2 in Cinemas on 25th August.”The poster depicts Ayushmann in a peculiar persona. Only his face is visible to the audience as he emerges from behind a bright curtain while Ananya could be seen looking at Ayushmann’s character.",
        category: "Bollywood",
    },
    {
        id: 10,
        heading: "Kangana Ranaut Calls Ranbir Kapoor, Alia Bhatt's Marriage Fake, Claims He 'Begged' Her To Date Him",
        image: "https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/31/1252486-kangana-vs-ranbiralia.jpg",
        description: "Kangana Ranaut has brought her reported past with Hirthik Roshan into the present once again on social media and shared that she was scammed by a person pretending to be the Bollywood actor. Kangana took to her Instagram stories and wrote:'Film mafia has always indulged in criminal activities, this superstar who I dated later claimed that I was dating his imposter. He used to use different numbers and accounts to chat with me, he also hacked my account and operated in a shady way. I thought he was going through a divorce but later I found out that had nothing to do with the shady behaviour...'",
        category: "Bollywood",
    },
    {
        id: 11,
        heading: "Bollywood News: Ajay Devgn Posts This As ‘Once Upon a Time in Mumbaai’ Clocks 13 Years",
        image: "https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/30/1252327-collage-maker-30-jul-2023-04-12-pm-6206.jpg",
        description: "Actors Ajay Devgn, Emraan Hashmi, and Kangana Ranaut starrer gangster drama film ‘Once Upon a Time in Mumbaai’ turned 13 on Sunday. To mark the occasion, actor Ajay Devgn took to his Instagram account and shared a picture which he captioned, “Once upon a time in Mumbai (metro) #13YearsOfOnceUponATimeInMumbai.” In the picture, the ‘Bholaa’ actor could be seen sitting inside Mumbai metro and looking outside the window. Helmed by Milan Luthria and produced by Ektaa Kapoor ‘Once Upon a Time in Mumbai’ also starred Prachi Desai and Randeep Hooda in pivotal roles.",
        category: "Bollywood",
    },
    {
        id: 12,
        heading: "Tamannaah Bhatia Soars Temperature In Glamorous Red Saree, Pics Inside",
        image: " https://english.cdn.zeenews.com/sites/default/files/2023/07/30/1252140-3638838541887728408496525190102304527832405n-1.jpg",
        description: "Reminding us of Lust Stories 2, Tamannaah Bhatia dropped pictures from a recent photoshoot. Looking sultry in a red saree, 'Tamannah infused the traditional ensemble with sexy boldness.Taking to Instagram, Tamannaah Bhatia wrote,Jailer audio launch![PS:Trust @falgunishanepeacockindia to always make you feel your glamorous best!.']",
        category: "Bollywood",
    },
    {
        id: 13,
        heading: "Elon Musk Takes A Dig At Greta Gerwig's 'Barbie,' The Reason Will Make You Go LOL",
        image: "https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/26/1249285-barbie-movie.png",
        description: "While Greta Gerwig's 'Barbie' film set several box office records, it faced scrutiny from some who believed that it portrays anti-man feminism. Seems like Tesla CEO Elon Musk also did not like the film. He recently took to Twitter and slammed the film,'It you take a shot every time Barbie says the word ‘patriarchy’, you will pass out before the movie ends.'",
        category: "Bollywood",
    },
    {
        id: 14,
        heading: "Ananya Panday opens up on Suhana Khan’s debut with The Archies, reveals if she sees her as a threat",
        image: "https://st1.bollywoodlife.com/wp-content/uploads/2023/07/Untitled-design-8-1.png?impolicy=Medium_Widthonly&w=1280&h=900",
        description: "Bollywood BFFs Suhana Khan and Ananya Panday never miss a chance to give a shout out to each other. While Ananya has been working in the Hindi film industry for about four years now, Shah Rukh Khan’s daughter Suhana Khan is all set to foray into the showbiz world with Zoya Akhtar’s The Archies. Ahead of the film’s release, Ananya Panday in a recent interview opened up on Suhana Khan’s much-awaited debut. The Liger actress said that her entry in Bollywood will definitely be a competition, but a healthy one. ",
        category: "Bollywood",
    },
    {
        id: 15,
        heading: "Shehnaaz Gill reveals she has been betrayed and dumped in her relationships",
        image: "https://cdn.siasat.com/wp-content/uploads/2023/06/shehnaaz-gill-13-660x660.webp",
        description: "Shehnaaz Gill, a much-loved actress, is well-known for her unending devotion to her supposed partner, Sidharth Shukla, who died in his 40s. Shehnaaz lost herself after his passing and found it difficult to cope with her sorrow. But now that the actress has returned to her former self and resumed acting, her personal life frequently makes the news. Shehnaaz was recently questioned by Instant Bollywood if she had ever experienced a romantic betrayal.She said that she has never betrayed anyone but she has been betrayed always. According to her, 'When one comes to know that their partner has a roving eye, one steps back.'",
        category: "Bollywood",
    },
    {
        id: 16,
        heading: "Janhvi Kapoor And Rajkummar Rao’s Mr And Mrs Mahi To Hit The Theatres On This Date",
        image: "https://static.india.com/wp-content/uploads/2023/07/Untitled-design-39.jpg",
        description: "National Award winner Rajkummar Rao and Janhvi Kapoor have reunited for their upcoming project, Mr and Mrs Mahi. The upcoming film is a romantic sports drama that has been on the radar of movie lovers for a while now. The much-awaited project is Rajkummar and Janhvi’s second collaboration after the 2021 horror thriller Roohi. The sports drama, helmed by Sharan Sharma, went on the floors in May last year. Now, the release date of the film has been announced. Mr and Mrs Mahi will hit the theatres in 2024.",
        category: "Bollywood",
    },
    {
        id: 17,
        heading: "Kriti Sanon turns producer, launches Blue Butterfly Films",
        image: "https://st1.bollywoodlife.com/wp-content/uploads/2023/07/FotoJet-13.jpg?impolicy=Medium_Widthonly&w=1280&h=900",
        description: "Kriti Sanon is the latest Bollywood actress who has turned producer. The actress was last seen in the much talked about movie, Adipurush. The actress started her career with Heropanti and has seen a steady journey since then in Bollywood. While this year, Kriti Sanon has been making a ton of noise with movie releases and back to back announcement, there is more left for the actress to unfold in the coming half year. One being, her venturing into producing films and now donning the responsible hat of a producer through her production house ‘Blue Butterfly Films’.",
        category: "Bollywood",
    },

    {
        id: 18,
        heading: "Have Katrina Kaif and Alia Bhatt also left Farhan Akhtar's Jee Le Zaraa post Priyanka Chopra's exit? Here's what we know",
        image: "https://cdn.dnaindia.com/sites/default/files/2023/07/04/2597754-whatsapp-image-2023-07-04-at-17.17.39.jpeg?im=FitAndFill=(1200,900)",
        description: "Recent reports had claimed that after Priyanka Chopra opted out of Farhan Akhtar's Jee Le Zaraa, the remaining two leads - Katrina Kaif and Alia Bhatt - had expressed reservations too.Farhan Akhtar’s ambitious and long-delayed project Jee Le Zaraa is in doldrums. Reports were doing rounds about both Katrina Kaif and Priyanka Chopra leaving the film, leaving only Alia Bhatt from the principal cast. The reports are only partly true. As it had been reported earlier, Priyanka has indeed left the film on account of the delay",
        category: "Bollywood",
    },
    {
        id: 19,
        heading: "Kajol calls Shah Rukh Khan ‘poor guy’ recalling a hilarious incident with the superstar",
        image: "https://st1.bollywoodlife.com/wp-content/uploads/2023/07/kanagankaran-1.png?impolicy=Medium_Widthonly&w=1280&h=900",
        description: "Kajol and Shah Rukh Khan share the greatest bond ever, and it's rare to see this kind of friendship. Kajol and SRK are buddies, and their bond is something that will make you want to have something similar like this. Both stars are super successful today and are doing absolutely great in their respective careers, and they have come a long way. In her recent interview, Kajol mentioned one incident that made her call SRK a poor guy at that time. Kajol shared one of her anecdotes from her blockbuster film Dilwale Dulhania Le Jaayenge along with Pathaan star, where she said that he got a frozen shoulder after he picked her up for a photoshoot for the said film. In an interaction with Curly Tales, Kajol sympathises with the Jawaan actor even now, and because of that, she feels extremely bad for him.",
        category: "Bollywood",
    },
    {
        id: 20,
        heading: "Rocky Aur Rani Kii Prem Kahaani box office collection: Alia Bhatt, Ranveer Singh new movie soars on day 2",
        image: "https://st1.bollywoodlife.com/wp-content/uploads/2023/07/RARKPK-1.png?impolicy=Medium_Widthonly&w=1280&h=900",
        description: "Karan Johar directed new movie Rocky Aur Rani Kii Prem Kahaani is entertaining fans. It has Alia Bhatt playing Rani and Ranveer Singh as Rocky in a love story drama that showcases differences in cultures in India, breaks stereotypes and more. And after a decent opening on day 1 at the movies, Rocky Aur Rani Kii Prem Kahaani day 2 box office collections are out. And the movie has seen some growth though not that great on the first Saturday.",
        category: "Bollywood",
    },

    {
        id: 21,
        heading: "Samsung Mobile head sees foldables mainstreaming, headed for 100 million annual sales",
        image: "https://images.indianexpress.com/2023/07/samsung-1.jpg",
        description: "The foldable form factor is already becoming mainstream and in a few years will record annual sales of over 100 million units, TM Roh, President & Head of Mobile Business, Samsung Electronics told indianexpress.com in Seoul last week. According to him, this year will be an essential tipping point for the segment with Samsung projecting global sales across brands of over 30 million units, especially with the improvements in its affordable foldable model.",
        category: "Technology",
    },
    {
        id: 22,
        heading: "iPhone 15 Pro to achieve thinner bezels using LIPO display tech: Report",
        image: "https://images.indianexpress.com/2023/07/iphone-14-pro.png?w=640",
        description: "As tradition goes, Apple will unveil its highly anticipated iPhone 15 series in the second or third week of September. A new report from Bloomberg now suggests that, with the iPhone 15 Pro, Apple will inch a step closer to its goal of creating the perfect smartphone, which began with the launch of the revamped iPhone X with a bezel-less display.",
        category: "Technology",
    },
    {
        id: 23,
        heading: "Aided by AI language models, Google’s robots are getting smart",
        image: "https://images.indianexpress.com/2023/07/google-robots.jpg?w=640",
        description: "Google has recently begun plugging state-of-the-art language models into its robots, giving them the equivalent of artificial brains. The secretive project has made the robots far smarter and given them new powers of understanding and problem-solving.Two Google engineers, Ryan Julian, left, and Quan Vuong, successfully instruct Google’s new robotics model, RT-2, to “move the Volkswagen to the German flag,” at Google’s robotics division in Mountain View, Calif., July 26, 2023. Google has recently begun plugging state-of-the-art language models into its robots, giving them the equivalent of artificial brains. (Kelsey McClellan/The New York Times)",
        category: "Technology",
    },
    {
        id: 24,
        heading: "Elon Musk replacing ‘Tweet’ button with ‘Post’? X braces for another big change",
        image: "https://images.indianexpress.com/2023/07/twitter-x-rebrand-1.jpg?w=640",
        description: "Twitter is in a state of flux, as it tries to shed its old skin and emerge as a new creature: X. The website is still littered with remnants of its past, such as the words “Twitter” and “tweet”, even as the X logo is slapped across the platform now. But the transition is an ongoing process and some users have noticed another change – the X website is testing the replacement of the ‘Tweet’ button with a ‘Post’ button.",
        category: "Technology",

    },
    {
        id: 25,
        heading: "One industry where humans may always be better than AI",
        image: "https://images.indianexpress.com/2023/07/Robot-preacher-mindar-20230729.jpg?w=640",
        description: "The recent rise of ChatGPT and other artificial intelligence tools brings both excitement and anxiety to the world. Excitement for the possibilities that these breakthrough technologies present. Anxiety about how many of us will be made redundant by them. What are the jobs that AI can take and what are the jobs that AI cannot?The Organisation for Economic Co-operation and Development says that 27 per cent of all jobs rely on skills that can be automated using artificial intelligence systems. While robotic tools have been affecting blue-collar jobs for decades now, the new AI systems are poised to do something similar to white-collar jobs, with everyone from lawyers and economists to writers and administrative staff being affected.",
        category: "Technology",

    },
    {
        id: 26,
        heading: "iPhone 15: 11 things we know about Apple’s next-gen smartphone series",
        image: "https://images.indianexpress.com/2023/07/iphone-15-pro-renders.jpg?w=640",
        description: "We’re mere weeks away from September, the time best-known for the debut of the new iPhone. Traditionally, Apple has hosted its flagship event every September, during which it reveals the new iPhone lineup as well as other must-have gadgets for the holiday season. While the last few generations of iPhones have mostly delivered iterative upgrades, the iPhone 15 series is expected to deliver a generational leap over last generation models. Here are all the new changes we can expect from the upcoming iPhone 15 series.",
        category: "Technology",

    },
    {
        id: 27,
        heading: "ISRO successfully places seven Singaporean satellites into intended orbit",
        image: "https://images.indianexpress.com/2023/07/F2QIexIbYAAlpzd.jpg?w=640",
        description: "ISRO successfully launched its proven PSLV rocket carrying seven Singaporean satellites Sunday from Satish Dhawan Space Centre in Sriharikota, Andhra Pradesh and placed them into intended orbits.Around 23 minutes after lift-off, the primary satellite got separated and it was followed by six other co-passenger satellites, which were deployed into the intended orbits sequentially, ISRO said.",
        category: "Technology",

    },

    {
        id: 28,
        heading: " What is FraudGPT, dark web’s dangerous AI for cybercrime?",
        image: "https://images.indianexpress.com/2023/07/Outer-Space-1.jpg?w=640",
        description: "Artificial Intelligence has taken the world by storm. While AI technologies promise to make life seemingly effortless, there is a thin line between what’s on paper and what’s possible. In the last six months, we witnessed the boundless possibilities of AI and also came up close with its potential threats in terms of misinformation, deepfakes, and loss of human jobs.From ChaosGPT to the dark web harnessing the power of AI to wreak havoc, all have been dominating news feeds in the past few months. Now, there seems to be a new dimension to the threat factor of AI. After WormGPT, which was known to aid cybercriminals, there is now a more threatening AI tool. According to reports, various actors on the dark web marketplaces and Telegram channels are promoting a generative AI for cybercrime known as FraudGPT.",
        category: "Technology",

    },

    {
        id: 29,
        heading: " Understanding mixed reality headsets: Will they replace smartphones?",
        image: "https://images.indianexpress.com/2023/07/spatial-computing-apple-vision-pro-featured.jpg?w=640",
        description: "Many tech enthusiasts believe that smartphones have reached their peak and that there is little room for further improvement in the current form factor. This is partly true, as smartphones have not seen the kind of breakthrough innovations that they did a decade ago. The next big thing in computing, according to some, is mixed-reality headsets. These devices are expected to usher in a new wave of computing, following the mainframes, PCs, and smartphones.",
        category: "Technology",

    },
    {
        id: 30,
        heading: "Almost 40% of the world is on Facebook now, but growth has slowed in home market",
        image: "https://images.indianexpress.com/2023/07/meta-llama2-microsoft-1.jpg?w=640",
        description: "In its second-quarter result announcement on Thursday, Meta revealed that Facebook reached over 3 billion monthly active users as of June 30 – or almost 40% of the world population. That’s a 6% increase from a year ago.However, the company also revealed that its user growth in the US and Europe was sluggish, while most of the new users came from Asia-Pacific and the rest of the world.",
        category: "Technology",

    },
    {
        id: 31,
        heading: "How Logitech’s keyboard case transformed my iPad Pro into a perfect writing device",
        image: "https://images.indianexpress.com/2023/07/Apple-iPad-Pro-Logitech-.jpg?w=640",
        description: "As I was patiently waiting for the startup co-founder to arrive for the meeting, the person sitting next to me in the hotel lobby curiously asked about the laptop I was using. I corrected him, “Sir, it’s an iPad Pro with a keyboard case.” He looked at me, smiled, and replied… “Wow, I didn’t know you could use the iPad as a laptop replacement.”",
        category: "Technology",

    },
    {
        id: 32,
        heading: "Samsung Galaxy Z Fold 5, Galaxy Z Flip 5 Don't Offer Dust Resistance, but Future Foldables Might: Report",
        image: "https://i0.wp.com/www.brumpost.com/wp-content/uploads/2023/07/image-158.png?resize=1536%2C865&ssl=1",
        description: "Samsung unveiled the flagship Galaxy Z Fold 5 and Galaxy Z Flip 5 smartphones at the Galaxy Unpacked event last week alongside the Galaxy S9 series tablets and Galaxy Watch 6 series smartwatches. This year's Galaxy Z series foldable phones bring several improvements over the previous generation, but they lack some durability requirements. Like the Galaxy Z Fold 4 and Galaxy Z Flip 4, the new models also lacks dust resistance and retain an IPX8 build. Now, a Samsung executive has reportedly stated that the company is working to add dust resistance to its foldable smartphones.",
        category: "Technology",

    },

    {
        id: 33,
        heading: " Fire-Boltt Gladiator Plus Smartwatch With 1.96-Inch AMOLED Display, Bluetooth Calling Launched in India",
        image: "https://i.gadgets360cdn.com/large/Fire-Boltt_Gladiator_Plus__main_1690795399330.jpg?downsize=950:*",
        description: "Fire-Boltt Gladiator Plus smartwatch has been launched in India under Rs. 3,000. The smartwatch comes with a 1.96-inch AMOLED display with a resolution of 410x502 pixels and 60Hz refresh rate. The display can reach up to 600 nits of peak brightness. The smartwatch features Bluetooth calling and smart health sensors like a heart rate monitor, sleep tracker, and female health monitor. It also supports over 115 sports modes and is IP67-rated for water and dust resistance. The wearable device is claimed to last for up to seven days on a single charge.",
        category: "Technology",

    },
    {
        id: 34,
        heading: "iPhone 15 Pro to Feature Titanium Edges, Apple's New 3nm Chip, and Repair-Friendly Internals: Mark Gurman",
        image: "https://i.gadgets360cdn.com/large/iphone_14_space_black_1689761321163.jpg?downsize=950:*",
        description: "iPhone 15 series — comprising the iPhone 15, iPhone 15 Plus, iPhone 15 Pro, and iPhone 15 Pro Max — are expected to make their debut this year. Apple's next generation of iPhone models are likely to bring several hardware upgrades, according to details that have recently surfaced online. The iPhone 15 models are said to feature a USB Type-C port and upgraded rear cameras, while the Pro models might feature a new 3nm chip, titanium edges, improved zoom performance, and easily repairable internals, just like the iPhone 14 that was launched last year.",
        category: "Technology",

    },
    {
        id: 35,
        heading: "Redmi 12, Infinix GT 10 Pro, Samsung And More Phones Launching In August 2023: Full List",
        image: "https://images.news18.com/ibnlive/uploads/2023/07/phone-launches-india-2023-16908012703x2.jpg?impolicy=website&width=510&height=356",
        description: "Another month is about to start in 2023 and that means it is time for new smartphone launches in the market. While the big ticket products will be making their way from September onwards, there is still a lot to look forward to for consumers, especially those who are looking for an upgrade across different price points. Brands like Xiaomi, iQOO, Infinix, Motorola and a few more are lining up their launches and here’s a look at the phones that will be available for buyers in the coming days.",
        category: "Technology",

    },
    {
        id: 36,
        heading: "Meta's Threads bolsters retention after losing over half of users: Report",
        image: "https://www.livemint.com/lm-img/img/2023/07/30/600x338/META-THREADS-32_1690090286032_1690706207835.jpg",
        description: "Meta Platforms executives are placing a strong emphasis on increasing user retention for Threads, their recently launched Twitter rival. CEO Mark Zuckerberg informed employees on Thursday that the app experienced a significant drop in users, losing more than half of its user base in the weeks following its highly publicized launch.",
        category: "Technology",

    },
    {
        id: 37,
        heading: "'Slack is down, finally peace': Netizens react as messaging app stops working",
        image: "https://www.livemint.com/lm-img/img/2023/07/27/600x338/SLACK_1690451155152_1690451155460.JPG",
        description: "The popular messaging app for the workplace, Slack is down for users across the globe and people are sharing the inconvenience of using the app. The reasons for the outage is not clear, however, those who reported issues 70 per cent said they were unable to send messages, 16 per cent have issues with the Slack app and 14 percent with server connection according to the downdetector.com.",
        category: "Technology",

    },
    {
        id: 38,
        heading: "Twitter rival Threads rolls out ‘Following’ tab. Here's how it works..",
        image: "https://www.livemint.com/lm-img/img/2023/07/26/600x338/META-THREADS--2_1688989955128_1690360210580.JPG",
        description: "Threads, the platform developed by Mark Zuckerberg, has unveiled a fresh addition to its features called the 'Following' tab. This new tab will enable users to view posts from the people they follow in a chronological order. ",
        category: "Technology",

    },
    {
        id: 39,
        heading: "Apple’s next 11.1-inch, 13-inch iPad Pro variants: What we know so far",
        image: "https://images.indianexpress.com/2022/12/iPad-Pro-2022.jpg?w=640",
        description: "Apple is working on new iPad Pro models, which are expected to arrive in 2024. These new iPad Pros are expected to be the brand’s most powerful tablets yet and are also expected to launch with bigger displays.Here’s all we know about the upcoming iPad Pro models so far.As per a new report by MacRumors, Display Analyst Ross Young said Apple’s next iPad Pro models could launch in 2024 and come with bigger OLED display panels. The report also adds that despite the slightly larger screens the new iPads could have even slimmer bezels, and hence, the same overall size.",
        category: "Technology",

    },
    {
        id: 40,
        heading: "How to setup user profiles on Disney+ Hotstar",
        image: "https://images.indianexpress.com/2023/07/disney-plus-hotstar-user-profiles.jpg?w=640",
        description: "When Disney+ Hotstar unveiled its revamped Android and iOS app a few months ago, one of the prominent new features of the update was the ability to set various user profiles. That allowed users to share their subscription with friends and family, especially the Premium plan, letting users stream content in up to 4K resolution on up to four screens simultaneously.",
        category: "Technology",

    },
    {
        id: 41,
        heading: "BTS' V surprises Jungkook during music show recording; Will the two shoot Seven dance challenge?",
        image: "https://www.pinkvilla.com/images/2023-07/385277163_bts-v-jungkook.jpg",
        description: "BTS' Jungkook performed live at the SBS Inkigayo music show on July 30 (KST). The Seven singer took home his music show win giving his best performance for his fans. What caught everyone's eyes was his fellow member's sudden surprise on stage. Yes! One of the best members surprised Jungkook and the two were seen vibing to Seven on stage together. ",
        category: "Hollywood",
    },

    {
        id: 42,
        heading: "Barbie Box Office’s Success Has Led Hollywood To Produce A Plethora Of Doll-Based Movies, Here’s What’s Happening!",
        image: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/07/hollywood-studios-already-in-stampede-to-make-barbie-style-toy-movies-001.jpg",
        description: "Hollywood studios are reportedly already in the midst of a “stampede” to make ‘Barbie’-style toy movies.New films based on the hit American Girl and miniature Polly Pocket dolls –both made by Barbie manufacturer Mattel – are said to have been given the green light.",
        category: "Hollywood",
    },
    {
        id: 43,
        heading: "Amanda Bynes Opts For A New In-Patient Mental Health Centre Just A Week After She Chose Out-Patient Treatment",
        image: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/07/amanda-bynes-checks-into-new-in-patient-mental-health-centre-01.jpg",
        description: "Actress Amanda Bynes has checked into a new mental health treatment centre as she continues to work on her illness.Sources told tmz.com that Amanda checked herself into an intensive inpatient mental health treatment centre in Orange County at the beginning of July, nearly a week after checking out of a Los Angeles area mental health facility for outpatient treatment.",
        category: "Hollywood",
    },
    {
        id: 44,
        heading: "What Not To Wear Fame Trinny Woodall Claims She Has Made Many Beauty Mistakes Including Fillers So That She Doesn’t Look Skeletal: “I Have Botox Twice A Year”",
        image: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/07/trinny-woodall-i-made-so-many-beauty-mistakes-when-i-was-younger-001.jpg",
        description: "Trinny Woodall has made “so many” beauty mistakes over the years.The 59-year-old stylist – who launched her own Trinny Beauty line in 2017 – used to plaster on fake tan to hide her acne and has been left with sun damage as a result of basking outside to get a natural glow.Talking to Woman and Home magazine, she said: “I made so many beauty mistakes when I was younger. When I had bad acne, I compensated by wearing a lot of fake tan. I went in the sun too, so I had sun damage.”",
        category: "Hollywood",
    },
    {
        id: 45,
        heading: "Selena Gomez celebrates women in her life, looks radiant while enjoying time with friends at bachelorette",
        image: "https://www.pinkvilla.com/images/2023-08/2141540915_selena-gomez.jpg",
        description: "Selena Gomez has been having the time of her life as she enjoys hanging out with her friends and looks forward to the future. The pop star is currently busy celebrating one of her best friends Connar Franklin who is about to get married. Here's what the 31-year-old is up to with her girl gang at the bachelorette party and the sweet message she has for the bride.",
        category: "Hollywood",
    },
    {
        id: 46,
        heading: "Big Brother 25: Where and how to watch reality series? Release date, host, contestants, and other details",
        image: "https://www.pinkvilla.com/images/2023-08/1249945197_.jpg",
        description: "American reality series Big Brother is back with a brand-new season and the upcoming 25th season is about to be bigger and better. Exciting details about the news installment were revealed during the Big Brother 25th Anniversary Special and here's everything you need to know about it including the release date, host, contestants, and more.",
        category: "Hollywood",
    },
    {
        id: 47,
        heading: "Love Island couples emotional rollercoaster update: Drama, dumpings, and potential rekindlings",
        image: "https://www.pinkvilla.com/images/2023-08/1899533150_mv5bmzbjytljzjutm2y0ns00ntm2lthim2utyzg0mgu1mtrlnta4xkeyxkfqcgdeqxvymta0ndg2nzu3-_v1_-1.jpg",
        description: "Love Island drama unfolded as dumped contestants Mitch Taylor and Ella Barnes were spotted holding hands while returning to the UK, just missing out on the show's final. Alongside them were axed pair Scott van-der-Sluis and Abi Moores, who seemed in high spirits despite their romance fizzling out. Aftersun interviews revealed some awkward moments, leaving fans wondering if any sparks will reignite or if it's all over for good. As the remaining couples battle it out for the Love Island 2023 crown and £50,000 prize, emotions run high in the villa. Let's dive into the latest updates and drama from the Love Island series finale.",
        category: "Hollywood",
    },
    {
        id: 48,
        heading: "New Paddington Movie Starring Ben Whishaw Continues Filming In The UK Despite SAG-AFTRA Strike In Hollywood- Here’s Why!",
        image: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/07/new-paddington-movie-shooting-despite-hollywood-strike-001.jpg",
        description: "The new ‘Paddington’ movie is reportedly shooting despite the strike that has brought Hollywood to a standstill.‘Paddington in Peru’ starring Ben Whishaw, 42, is said to be filming in the UK as part of a handful of productions which are going ahead amid the 171,500-strong actors’ and writers’ walk out.",
        category: "Hollywood",
    },

    {
        id: 49,
        heading: "BTS’ Jungkook donates 1 Billion KRW to SNU Children’s Hospital; ‘I hope that it will be of some help’",
        image: "https://www.pinkvilla.com/images/2023-04/1230024267_312461539_122128953981764_6598520975438600877_n_1280*720.jpg",
        description: "BTS’ Jungkook has once again stunned ARMYs but this time not with his emotive vocals or immaculate visuals but with a generous gesture. In a statement released by Seoul National University Children’s Hospital earlier today, it has been revealed that the BTS maknae has made a donation of 1 billion KRW (a little over $758,000) to the hospital to support the treatment of child patients. The said donation was reportedly made just last week on April 14. ",
        category: "Hollywood",
    },
    {
        id: 50,
        heading: "Thai actor-singer Bright Vachirawit Chivaaree on his fave things to do in Bangkok and fashion essentials",
        image: "https://onecms-res.cloudinary.com/image/upload/s--d7NpVsl---/c_crop,h_1002,w_1336,x_1,y_86/c_fill,g_auto,h_622,w_830/fl_relative,g_south_east,l_mediacorp:cna:watermark:2021-08:cna,w_0.1/f_auto,q_auto/v1/mediacorp/cna/image/2023/03/23/230322_CNA_bright34363_1.jpg?itok=8obOsjLt",
        description: "Bright Vachirawit Chivaaree’s mother definitely knew what she was doing when she named him. Just look at how bright his star is right now.He's one of Thailand’s most popular stars, and with his social media numbers at 17.6 million followers on Instagram and 4.6 million on Twitter, we’re not surprised at all.After all, Bright is a household name in Thailand, having hosted his very first variety show, Strawberry Krubcake, when he was only 15 years old.",
        category: "Hollywood",
    },
    {
        id: 51,
        heading: "3 Reasons To Catch The Premiere Of C-Drama “Twilight”",
        image: "https://0.soompi.io/wp-content/uploads/2023/07/31024144/twilight-1-1-2.jpg",
        description: "C-drama “Twilight” — not to be confused with the American film franchise “Twilight” — has nothing to do with humans and vampires.Instead, it takes us into the minds of mystery novel writer Qi Lian Shan (Ren Jia Lun) and psychological counselor Liu Xia (Angelababy) who have the ability to understand the functioning of the human mind. When these two come together, it is nothing short of a rollercoaster of misadventures, romance, and humor. Here is a look at episodes one and two, which leave you curious and wanting more.",
        category: "Hollywood",
    },
    {
        id: 52,
        heading: "Kim Sejeong Confirmed To Make Comeback As An Artist",
        image: "https://6.soompi.io/wp-content/uploads/image/20230727031441_kim-sejeong-comeback.jpeg?s=900x600&e=t",
        description: "Kim Sejeong is making a comeback with new music! On July 27, OSEN reported that Kim Sejeong will make a comeback as an artist in September.In response to the report, Kim Sejeong’s agency Jellyfish Entertainment shared, “Kim Sejeong will release a new album in September.” This is Kim Sejeong’s comeback as an artist for the first time in two years since her second mini album “I’m,” which was released in 2021.",
        category: "Hollywood",
    },
    {
        id: 53,
        heading: "Kim Sejeong Announces Dates And Locations For 1st Concert Tour “The 門”",
        image: "https://6.soompi.io/wp-content/uploads/image/20230801013457_Kim-Sejeong-The-%E9%96%80-1.jpeg?s=900x600&e=t",
        description: "Kim Sejeong is going on tour!On August 1 at midnight, Kim Sejeong announced her first concert tour “The 門.”In the newly released poster, Kim Sejeong reveals the dates and location for her upcoming tour. After kicking off her tour in Seoul on September 23 and 24, Kim Sejeong will head to Hong Kong, followed by Manila, Jakarta, Taipei, Tokyo, Singapore, Kuala Lumpur, Bangkok, Melbourne, and Sydney.",
        category: "Hollywood",
    },
    {
        id: 54,
        heading: "Netflix under fire: AI job listings spark controversy amid Writers Guild strike",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/31/550x309/NETFLIX-MICROSOFT-ADVERTISING-0_1690825787039_1690825906541.JPG",
        description: "Netflix, along with other entertainment giants like Disney, has faced criticism for posting high-paying artificial intelligence (AI) positions during the ongoing Writers Guild of America (WGA) strike.As writers and actors demand better pay (with 87% of the guild's 170,000-plus performers earning no more than $26,000 a year), studios have posted lucrative AI job listings. Netflix's listing, which advertised a salary of up to $900,000, raised eyebrows.",
        category: "Hollywood",
    },
    {
        id: 55,
        heading: "Fresh perspective or old wounds? Depp V Heard - Netflix's tell-all documentary sparks heated debates among fans",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/31/550x309/Depp-Heard-Trial-0_1662540217375_1662540217375_1690810411763.jpg",
        description: "Johnny Depp and Amber Heard's trial captivated the world, and now it's making a comeback on Netflix. Depp V Heard, a three-part documentary series, is set to reexamine the infamous lawsuit between Johnny Depp and Amber Heard. But don't expect a rehash of the gossip and rumors; Netflix promises a fresh, impartial perspective.",
        category: "Hollywood",
    },
    {
        id: 56,
        heading: "Michelle Yeoh's 77-year-old husband is ex-CEO of Ferrari, know all about him",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/31/550x309/Michelle_Yeoh_1690775099038_1690775111277.jpg",
        description: "Michelle Yeoh recently married her longtime love, a 77-year-old man named Jean Todt in Geneva on July 27, 2023. The couple first met in June 2004 in Shanghai and got engaged just one month later. So she had been engaged to Todt for 19 years since July 2004. Interestingly, her husband Todt is the ex-CEO of Ferrari.After her marriage, Yeoh took to Instagram and posted pictures from the ceremony, writing: '19 years and YES!! we are married!! Thkq to our ‘families’ who love us for all these years . We love you and here’s to many more to come.'",
        category: "Hollywood",
    },
    {
        id: 57,
        heading: "‘Soulcatcher’ Netflix Polish Thriller: Release Date, Air time, Plot and more",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/29/550x309/soulcatcher_1690630902251_1690630902483.webp",
        description: "The story follows a tough military contractor on a mission to find a dangerous weapon that turns regular folks into heartless killers. But guess what? Things take an unexpected turn when his own brother becomes a victim of this deadly weapon!Starring the talented Piotr Witkowski as the lead character, and with a bunch of other amazing actors in key roles, 'Soulcatcher' is a rollercoaster of suspense and action. Bringing this thrilling tale to life is director Daniel Markowicz, who co-wrote the script alongside the brilliant Dawid Kowalewicz.",
        category: "Hollywood",
    },
    {
        id: 58,
        heading: "The Monkey King: Release Date, Trailer, and Everything We Know So Far",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/27/550x309/MonkeyThe_Monkey_King_u_00_19_24_02_1690475473247_1690475539226.jpg",
        description: "This movie is inspired by a Chinese character from 'Journey to the West,' a famous 16th-century Chinese novel. The Monkey King possesses extraordinary supernatural powers, but his biggest challenge is his own inflated ego.In 'The Monkey King,' you'll hear the voices of talented Asian actors from Hollywood, like Jimmy O. Yang as the Monkey King, Bowen Yang as the Dragon King, Jolie Hoang-Rappaport as Lin, Jo Koy as Benbo, Ron Yuan as Babbo, and Stephanie Hsu as the Mayor's Wife.",
        category: "Hollywood",
    },
    {
        id: 59,
        heading: "Strike strikes! 75th annual Emmy Awards postponed as actors' and writers' strike continues. Here's the new date",
        image: "https://www.hindustantimes.com/ht-img/img/2023/07/28/550x309/FILES-US-ENTERTAINMENT-TELEVISION-EMMYS-1_1690533459177_1690533487204.jpg",
        description: "The highly anticipated 75th Annual Emmy Awards, scheduled for Sept. 18, will not be gracing our screens as planned. Taking in account the actors' and writers' strikes that have thrown Hollywood into a state of limbo. USA TODAY has confirmed that the ceremony, hosted by the National Academy of Television Arts and Sciences and set to air on Fox, will be postponed to January 2024.",
        category: "Hollywood",
    },
    {
        id: 60,
        heading: "Hey, weirdos, do you have…’, Megan Fox reacts to criticism for not supporting friends Cancer Fund, fans furious",
        image: "https://i.insider.com/5ebf0b1df0f4191c324d3693?width=1000&format=jpeg&auto=webp",
        description: "American actress Megan Fox is facing criticism from fans after being accused of 'lacking generosity' for not contributing to her friend Brittney Boyce's father's cancer fund.",
        category: "Hollywood",
    },
    {
        id: 61,
        heading: "Study finds isometric exercises like planks twice as effective in lowering blood pressure; expert weighs in",
        image: "https://images.indianexpress.com/2023/07/plank_1200_getty.jpg?w=640",
        description: "Unlike what has long been considered, a new study claims that isometric exercises that require the body to be held in one position can be twice as effective as moderate-intensity aerobic activity. While the results showed that significant reductions in resting systolic and diastolic blood pressure occurred after all exercise types, it was specifically isometric exercises like planks and wall sits or wall squats that were most effective, reported the study published in the British Journal of Sports Medicine.",
        category: "Fitness",
    },
    {
        id: 62,
        heading: "With a throwback picture, trainer reveals how Ranveer Singh managed to look ‘jacked’",
        image: "https://images.indianexpress.com/2023/07/ranveer-singh_1200_2016.jpg?w=640",
        description: "Bollywood celebrities are at the peak of their fitness routine and have always managed to create awe around their transformation with the help of celebrity trainers. As such, when Lloyd Stevens, fitness trainer and transformation specialist, shared a throwback picture of actor Ranveer Singh from his 2016-Befikre days, we couldn’t help but go down the memory lane with Stevens, who opened up about how Singh managed to surprise everyone with his chiselled physique.",
        category: "Fitness",
    },
    {
        id: 63,
        heading: "Why six-pack abs are so hard to achieve – and maintain",
        image: "https://images.indianexpress.com/2023/07/charles-gaudreault-xXofYCc3hqc-unsplash-1.jpg?w=640",
        description: "Many people start going to the gym in the hopes of achieving what has long been seen as the holy grail of health and fitness: six-pack abdominal muscles (abs). But as many people who have tried will attest – including celebrities, such as comedian Eric André – this can be far more challenging than expected. André even equated the experience of trying to achieve a six-pack with being like a full-time job in and of itself. There are many reasons why “getting ripped” is so difficult. It requires sustained hard work and a strict diet – and may also come at the cost of good health.",
        category: "Fitness",
    },
    {
        id: 64,
        heading: "Malaika Arora’s yoga mantra: ‘Challenging yourself will only make you stronger’",
        image: "https://images.indianexpress.com/2023/06/malaika.jpg?w=640",
        description: "Malaika Arora is known not only for her impeccable style but also for her unparalleled fitness game. The actor never compromises on her workout routine and inspires all her fans to have a dedicated fitness regimen. She also keeps sharing snippets from her daily yoga sessions at the gym.Recently, Malaika took to Instagram to share snippets of her workout regimen. Her latest video will motivate you to take out your yoga mat and kickstart your yoga journey.",
        category: "Fitness",
    },
    {
        id: 65,
        heading: "Mira Kapoor does cycling on vacation to stay fit; here’s how it helps",
        image: "https://images.indianexpress.com/2023/07/mira-kapoor_200_insta.jpg?w=640",
        description: "Mira Kapoor has been quite influential with her approach to health and fitness. As such, the mother-of-two is often on point when it comes to enjoying herself while also ensuring she stays on track with her fitness routine even on vacation. Mira, who has been enjoying time off with husband Shahid Kapur in places like Switzerland, Greece, and Denmark, recently shared an Instagram Story on cycling in Copenhagen, the capital city of Denmark.",
        category: "Fitness",
    },
    {
        id: 66,
        heading: "Nursing mother Gauahar Khan resumes resistance training postpartum; expert weighs in",
        image: "https://images.indianexpress.com/2023/07/gauahar-khan_featured.jpg?w=640",
        description: "Gauahar Khan has been proving that if you have been consistent with workouts before pregnancy and childbirth, it can help you get back to your fitness routine much more quickly. As such, the nursing mother who has been on a weight loss spree for the past two months and even resumed her fitness journey within a span of 10 days after delivering her first child with Zaid Darbar, has been giving us some food for thought. The actor was recently seen doing resistance training and even boxing with her coach.",
        category: "Fitness",
    },
    {
        id: 67,
        heading: "Australian man smashes world record of most pushups done in an hour; tips to keep in mind when performing the exercise",
        image: "https://images.indianexpress.com/2023/07/guinness-world-record.jpg?w=640",
        description: "Daniel Scali, a 30-year-old Australian fitness and health enthusiast, has reclaimed the record for the most pushups done in an hour. He successfully completed an astounding 3,249 pushups, breaking the record of 3,206 achieved by fellow Aussie, Lucas Helmke, in November 2022. Scali had previously set the record in April 2022 with 3,182 pushups.",
        category: "Fitness",
    },
    {
        id: 68,
        heading: "Virat Kohli believes ‘every day should be a leg day’",
        image: "https://images.indianexpress.com/2023/07/virat-kohli-fitness_insta.jpg?w=640",
        description: "https://english.jagran.com/lifestyle/virat-kohlis-leg-day-mantra-shows-why-you-should-include-leg-workouts-in-your-routine-10087475",
        category: "Fitness",
    },
    {
        id: 69,
        heading: "Struggling with stiff shoulders? Try these 3 simple exercises to relieve pain",
        image: "https://images.indianexpress.com/2023/07/stiff-shoulders.jpg?w=640",
        description: "With a rise in sedentary lifestyles and long working hours on the laptop, most of us have struggled with stiff and tight shoulders. While over-the-counter pain-relieving medications can help provide temporary relief, a number of exercises can help ease the pain for good and improve posture at the same time.Sharing the same through her Instagram post, celebrity fitness instructor Yasmin Karachiwala demonstrated some exercises that can help with stiff shoulders.",
        category: "Fitness",
    },
    {
        id: 70,
        heading: "‘Proud coach’ opens up about Maniesh Paul’s fitness transformation within a span of three weeks",
        image: "https://images.indianexpress.com/2023/06/maniesh-paul-transformation_200_insta.jpg?w=640",
        description: "Television host turned actor Maniesh Paul has undergone a jaw-dropping transformation for his debut web series Rafuchakkar. He gained 10 kgs and then lost 15 kgs, all in around four months.The show's trailer offered a few glimpses of Maniesh's varied avatars. While one of his looks required him to gain weight to resemble a pot-bellied plump middle aged man, another look portrayed him as a ripped body builder.",
        category: "Fitness",
    },
    {
        id: 71,
        heading: "Practise this Pranayama to reap maximum health benefits",
        image: "https://images.indianexpress.com/2023/06/pranayama-1.jpg?w=640",
        description: "Breathing exercises like Pranayama not only enhance physical health but also relax the mind, thereby promoting overall well-being. It is also believed that this breathing technique enables individuals to balance the tridoshas (three types of nature) –vata, pitta and kapha. These doshas often lead to a myriad of health issues. Which is why it is beneficial to improve one’s ability to control their breathing.",
        category: "Fitness",
    },
    {
        id: 72,
        heading: "How to start running today: a beginner’s guide",
        image: "https://www.verywellfit.com/thmb/fAPuEPddDGJ5D1tdD9zm-09NVXc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/how-to-start-running-the-absolute-beginners-guide-2911191-3231-1bc4d82ab0494200b126e521dd1c0edb.jpg",
        description: "There are so many reasons why millions of people around the globe enjoy running. Whether you're training for a race or logging miles for fun, running is good for your body and mind, and it requires very little equipment. All you need is a good pair of running shoes and the willingness to get started.",
        category: "Fitness",
    },
    {
        id: 73,
        heading: "Shy girl workouts’ aren’t just a great way to get fit – they may also help women gain confidence in the gym",
        image: "https://images.indianexpress.com/2023/06/john-arano-h4i9G-de7Po-unsplash.jpg?w=640",
        description: "An online trend that began since late 2022, the shy girl workout continues to grow in popularity. Targeted at women who may be beginners or have anxiety about going to the gym, the premise of shy girl workouts is simple. They are designed to use minimal space in the gym and only a couple of pieces of equipment – such as a pair of dumbbells. While the initial benefit of these workouts is that they can help women overcome their fear of going to the gym, they may also have the more long-term benefit of empowering them and helping them feel more confident about being in the gym says a PTI report quoting The Conversation.",
        category: "Fitness",
    },
    {
        id: 74,
        heading: "Weight Loss Workout: 4 Tips and Tricks for Losing Weight While Fasting",
        image: "https://images.news18.com/ibnlive/uploads/2023/07/image-46-16906959513x2.jpg?impolicy=website&width=510&height=356",
        description: "Whether it was for health, religious, cultural, or other reasons, all of us have tried fasting at some point. Although many people believe that fasting has health benefits, this misconception is dangerous. It’s a common misconception that you shouldn’t exercise when fasting. In actuality, exercising while fasting might be advantageous if you know the type of workout plan that is ideal for you. Even if there are a few things to bear in mind when exercising while fasting, it is advisable to keep going. Fitness expert Kushal Pal Singh from Anytime Fitness discusses how to plan exercises around fasts.",
        category: "Fitness",
    },
    {
        id: 75,
        heading: "Possible Side Effects of Taking Multivitamins on an Empty Stomach",
        image: "https://images.news18.com/ibnlive/uploads/2023/05/untitled-design-2023-05-30t162905.280-16854443673x2.jpg?impolicy=website&width=510&height=356",
        description: "When it comes to consuming multivitamins, timing and context matter. Taking them on an empty stomach can lead to certain side effects due to the concentrated nature of the vitamins and minerals. It is generally recommended to take multivitamins with a meal or snack to aid in their absorption and minimize any potential discomfort. Consuming them on an empty stomach may have potential side effects that individuals should be aware of. Let’s explore the possible consequences of taking multivitamins without food and provide helpful tips to maximize their effectiveness while minimizing any adverse effects.",
        category: "Fitness",
    },
    {
        id: 76,
        heading: "World Hepatitis Day 2023: How Acute Hepatitis Can Lead To Liver Cancer",
        image: "https://images.news18.com/ibnlive/uploads/2023/07/shutterstock_2181725607-16897404143x2.jpg?impolicy=website&width=510&height=356",
        description: "Acute hepatitis refers to the sudden onset of inflammation in the liver, typically caused by a viral infection. It is characterized by symptoms such as fatigue, jaundice (yellowing of the skin and eyes), nausea, vomiting, abdominal pain, and dark-colored urine. Acute hepatitis can be caused by different viruses, with the most common types being hepatitis A, B, and C. In most cases, acute hepatitis resolves on its own with supportive care, but some individuals may develop a chronic infection.",
        category: "Fitness",
    },
    {
        id: 77,
        heading: "Deepika Padukone stuns as she sports washboard abs: ‘Not so long ago…’",
        image: "https://images.indianexpress.com/2023/08/deepika-padukone_200_instaaa.jpg?w=640",
        description: "Trust Deepika Padukone to regularly give us fitness goals with her dedication and enviable physique. As such, the actor recently took everyone, including her husband and actor Ranveer Singh, by surprise as she dropped a picture displaying her toned abs. “Once upon a time…Not so long ago…,” wrote the Fighter actor. “A warning would’ve been nice,” wrote Ranveer in the comments section, and we could not agree more.Taking some inspiration from the 37-year-old, experts decode how to tone your abs.",
        category: "Fitness",
    },
    {
        id: 78,
        heading: "These 5 lifestyle changes will help lower your risk of cancer",
        image: "https://images.indianexpress.com/2023/01/cancer-1200-.jpg?w=640",
        description: "According to the World Health Organisation (WHO), cancer is the most prominent cause of death globally, with the number of people affected by the ailment increasing each year. The cancer statistics in India are grim as well with approximately 27 lakh people being diagnosed with cancer and cancer-related deaths amounting to 8.5 lakh in 2020, as per India against Cancer, an initiative to combat cancer. While advancements in technology have significantly elevated cancer care, it’s necessary to ensure some habits that can lower your risk of this deadly disease.",
        category: "Fitness",
    },
    {
        id: 79,
        heading: "Do you know what causes acidity?",
        image: "https://images.indianexpress.com/2022/10/acidity.jpg?w=640",
        description: "Who does not know the feeling of burning sensation in the chest and throat? One of the most common stomach-related issues, acidity which is also known as ‘acid reflux’, can be caused due to the overproduction of acid in the stomach.According to Healthline.com, if you have symptoms of acid reflux more than twice a week, you might have a condition known as gastroesophageal reflux disease (GERD). As per a 2019 study published in Research Gate, the prevalence of GERD in India ranges from 7.6 per cent to 30 per cent.",
        category: "Fitness",
    },
    {
        id: 80,
        heading: "Cut coffee intake if you have severe high BP: here’s why",
        image: "https://images.indianexpress.com/2022/12/Coffee-1200.jpg?w=640",
        description: "Drinking two or more cups of coffee a day may double the risk of death from cardiovascular disease among people with severe high  hea (160/100 mm Hg or higher) compared to non-coffee drinkers, according to research published in the open-access, peer-reviewed Journal of the American Heart Association (JAHA).In contrast, one cup of coffee and daily green tea consumption did not increase the risk of death related to cardiovascular disease at any blood pressure measurement, even though both drinks contain caffeine, the study, conducted among more than 18,600 men and women in Japan, found.",
        category: "Fitness",
    },

    {
        id: 81,
        heading: "LABNEH TOPPED SPICED CARROT CAKE",
        image: "https://img.delicious.com.au/Kl8Gm8gM/del/2017/05/spiced-carrot-cake-with-labneh-icing-46402-2.jpg",
        description: "This Carrot Cake recipe is a favourite of the team, and a great way to use up those over ripe bananas in the fruit bowl. Baking is easy with our cold pressed rapeseed oil - the one bowl method is the quick and easy way to get a cake on the table, and less washing up too! Topped with Yorkshire Dama Cheese Labneh, which is a spreadable yoghurt, it makes for a healthy replacement for cream cheese. It's a delicious bake.",
        category: "Food",
    },
    {
        id: 82,
        heading: "Eid ul Adha 2023: 5 delectable Phirni recipes that can easily be made at home",
        image: "https://st1.latestly.com/wp-content/uploads/2023/04/Eid-Sweet-Dishes.jpg",
        description: "Phirni, a creamy and luscious Indian dessert made with rice, milk, sugar, and aromatic spices, is a treat for your taste buds. In this article, we will share with you 5 delightful variations of Phirni that can be effortlessly prepared in the comfort of your own kitchen. These recipes offer a range of flavours, from traditional classics to contemporary twists, allowing you to savour the rich indulgence of Phirni with a unique twist. Get ready to tantalize your senses with these easy-to-follow recipes!",
        category: "Food",
    },

    {
        id: 83,
        heading: "Want A Healthy Tikki? Try This Delicious Chana Dal And Cabbage Tikki",
        image: "https://c.ndtvimg.com/2023-08/gq5bolgg_cabbage-tikki_625x300_01_August_23.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        description: "Crisp and flavourful tikkis are the quintessential desi snack. Whether you prefer them plain, with chutneys and sauces, or mixed with chaat - tikkis are always a delight. There are so many mouth-watering varieties: aloo tikki, soya tikki, paneer tikki and others. Now, tikkis are often considered an indulgence. But what if we told you that they can be enjoyed even while dieting? We have a special recipe for a high-protein tikki that you need to try: Chana Dal And Cabbage Tikki. This nutritious snack can easily be prepared at home with just a handful of ingredients. ",
        category: "Food",
    },
    {
        id: 84,
        heading: "Spot Idli Recipe | Hyderabadi Instant Spicy Idli On Tawa",
        image: "https://static.toiimg.com/thumb/msid-99818122,imgsize-103152,width-400,resizemode-4/99818122.jpg",
        description: "Spot Idli Recipe | Hyderabadi Instant Spicy Idli On Tawa with detailed photo and video recipe. An easy and simple idli recipe prepared on tawa without access to idli stand or steaming process. On top of it, it is loaded with unique street-style masala which makes it a lip-smacking snack breakfast meal recipe. It is typically loaded with all the spices and hence does not require any additional sides to it but tastes great with a simple hotel-style coconut coriander chutney.",
        category: "Food",
    },

    {
        id: 85,
        heading: "Spring Rolls | Crispy Veg Spring Roll Recipe",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2015/10/spring-rolls-recipe.jpg",
        description: "These Spring rolls are a popular Chinese snack of crispy rolls filled with a savory mixed vegetables stuffing. Hot handheld pockets of spiced veggies are wrapped and deep fried for an endlessly adaptable and delightfully dippable snack. This yummy recipe for crispy vegan Veg Spring Rolls can be made with whatever veggies you have on hand. I’m excited to show you how to make your favorite Indo-Chinese street food at home using just a few simple ingredients!",
        category: "Food",
    },
    {
        id: 86,
        heading: "Easy Pineapple Upside Down Cake (Eggless)",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2017/12/eggless-pineapple-upside-down-cake-recipe.jpg",
        description: "Eggless pineapple upside down cake recipe with step by step pics. One of the most loved cakes at my place is pineapple upside down cake. I make a simple, easy one bowl recipe of cake which has a soft crumb laced with the deliciousness of pineapple in each bite. It has a soft crumb with sweet pieces of pineapple in every bite, and looks so lovely on a plate!",
        category: "Food",
    },
    {
        id: 87,
        heading: "Momos Recipe | Dim Sum | Veg Momos",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/07/veg-momos-recipe.jpg",
        description: "Momos are a popular street food in northern parts of India. These are also known as Dim Sum and are basically dumplings made from flour with a savory stuffing. Learn to make these popular Tibetan recipe of easy veg momos from scratch with two folding techniques. The momos recipe is also vegan.",
        category: "Food",
    },
    {
        id: 88,
        heading: "Rava Dosa Recipe | Quick Suji Ka Dosa",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/05/rava-dosa-recipe.jpg",
        description: "Rava dosa (also known as Suji ka Dosa) is a quick and popular variant of dosa from the South Indian cuisine. These are crispy, netted and thin crepes made with semolina (rava or cream of wheat), rice flour, all purpose flour and spices. These are incredibly easy to make and require no grinding or fermentation, unlike the traditional Dosa Recipe. Make a truly crispy Rava Dosa recipe – one that you will make again and again for a quick breakfast or snack.",
        category: "Food",
    },
    {
        id: 89,
        heading: "Noodles Recipe | Veg Noodles Recipe",
        image: "https://www.vegrecipesofindia.com/wp-content/uploads/2018/09/veg-noodles.jpg",
        description: "This veg noodles recipe, made with all of your favorite fresh vegetables, is perfect for a quick a weeknight meal! Ready in just 30 minutes, this Chinese-style stir fried veggie noodles is kid-friendly and fully customizable.This easy stir fried veggie noodles recipe has just the right level of spice. Not too much heat, not very pungent, but still filled with so much flavor, this kid-friendly noodles recipe is the perfect family meal.",
        category: "Food",
    },
    {
        id: 90,
        heading: "No-Oil Vegetable Pulao Recipe",
        image: "https://c.ndtvimg.com/2023-01/bcdjpkg_pulao_625x300_31_January_23.jpg",
        description: "No-Oil Vegetable Pulao Recipe: Pulao is such a delicious recipe that we can make in few minutes. But today we are bring an amazing recipe of pulao which can be made without oil and it can be good option for those people who are weight watchers.",
        category: "Food",
    },

    {
        id: 91,
        heading: "Turkey Burgers",
        image: "https://hips.hearstapps.com/hmg-prod/images/turkey-burger-secondary-6481ed48cfc21.jpg?crop=0.669xw:1.00xh;0.0431xw,0&resize=980:*",
        description: "While they can have a reputation for being dry and bland, made right, turkey burgers are anything but. We love our recipe for one simple reason: We let it be. Instead of trying to make it into something it’s not, we embraced the flavors of the turkey instead of trying to cover 'em up.",
        category: "Food",
    },
    {
        id: 92,
        heading: "Turkey Zucchini Enchilada Casserole",
        image: "https://hips.hearstapps.com/hmg-prod/images/turkey-zucchini-enchilada-casserolepin-1658265755.jpg?crop=0.951xw:0.900xh;0.0493xw,0.0461xh&resize=980:*",
        description: "There are few things zucchini can't do, it seems. From grilled zucchini to zucchini soup and zucchini lattice lasagna, you can use it in so many different ways. Here, the summer squash is standing in for corn tortillas in this casserole recipe that takes the summer squash fully into the colder months.",
        category: "Food",
    },
    {
        id: 93,
        heading: "Chipotle Chicken Burrito Bowl",
        image: "https://hips.hearstapps.com/hmg-prod/images/copycat-chipotle-burrito-bowl-secondary-641dd68c6847f.jpg?crop=0.6666666666666666xw:1xh;center,top&resize=980:*",
        description: "While we’re all about switching things up, when we want a tried-and-true perfect meal, we always go back to the Chipotle chicken burrito bowl. It’s classic, reliable, and, best of all, completely customizable depending on our mood.",
        category: "Food",
    },
    {
        id: 94,
        heading: "Classic Sesame Noodles with Chicken",
        image: "https://www.eatingwell.com/thmb/YFxXsf55AMjJRknGDJYBN5CNc3U=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3759402-a9972fae1e0c429bb256bf8127941c2e.jpg",
        description: "Classic sesame noodles become a healthy meal with lean chicken and tons of veggies in this quick noodle recipe. Be sure to rinse the spaghetti until it's cold, then give it a good shake in the colander until it's well drained. Are you a spiralizing pro? Swap 5 cups of raw zucchini, carrot or other veggie 'noodles' for the cooked pasta.",
        category: "Food",
    },
    {
        id: 95,
        heading: "One-Skillet Bourbon Chicken",
        image: "https://www.eatingwell.com/thmb/P8R3SqakNwQ2sGev6FGfQNP0zjk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/one-skillet-bourbon-chicken-c671f5a991d14f73b314311909f75cc5.jpg",
        description: "Coating the chicken in cornstarch might seem like an extra step, but the reward is twofold: it gives the chicken a crispy exterior and also thickens the sauce. Legend has it that bourbon chicken was originally named after Bourbon Street in New Orleans; it can often be found on menus at Chinese American restaurants.",
        category: "Food",
    },
    {
        id: 96,
        heading: "3-Ingredient Teriyaki Edamame Sauté",
        image: "https://www.eatingwell.com/thmb/7zfnYf7GDbgr4iyQnrt-zdU8kXA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/EW-3-Ingredient-Dinners-for-Diabetes_Teriyaki-Edamame-Saute-06e5cf454b5f42c5a459d83e69fcd5ad.jpg",
        description: "Whip up this high-fiber, plant-based stir-fry for a quick and convenient dinner. Look for bottled teriyaki sauce labeled less sodium or reduced sodium to cut back on the salt without sacrificing flavor.",
        category: "Food",
    },
    {
        id: 97,
        heading: "Lentil Curry with Cauliflower Rice",
        image: "https://www.eatingwell.com/thmb/9ZajsSOBxWyKlH_K-uv_t8_vs64=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/lentil-curry-cauliflower-rice-2000-2bc5cfe87d9a462ca3820774b9f3abcc.jpg",
        description: "Combine precooked lentils (often located in the produce section of your grocery store) with an Indian-style simmer sauce for a super-fast and flavorful curry. Serving it over riced cauliflower bumps up the vegetable count and keeps carb servings in check. This 3-ingredient dinner (not counting salt, pepper and oil) is really as easy as it gets. To be mindful of the salt, look for simmer sauces with less than or close to 350 mg sodium per ¼-cup serving.",
        category: "Food",
    },
    {
        id: 98,
        heading: "Salmon Tacos with Pineapple Salsa",
        image: "https://www.eatingwell.com/thmb/RtI02K2pRrz9QGDE9pQZJAPPzCo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5691772-09412f91e1224c17a23a47b58915fb15.jpg",
        description: "An easy-to-make slaw served on the side of these salmon tacos makes for a filling and fast weeknight dinner. If you prefer more heat in these fish tacos, simply add a pinch or two of chipotle chile powder or cayenne with the chili powder.",
        category: "Food",
    },
    {
        id: 99,
        heading: "Quick Shrimp Puttanesca",
        image: "https://www.eatingwell.com/thmb/8mwBxtrJQAj1ndNy1YjMa5OJFJw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5691842-b2f4cd6fc27e4b1680502be7f3ce2f57.jpg",
        description: "Because refrigerated fresh pasta cooks much faster than dried pasta, this Italian-inspired pasta dish will be on the table lickety-split! Puttanesca, traditionally made with tomatoes, olives, capers, anchovies and garlic, gets shrimp for extra protein and artichoke hearts to boost the vegetable servings (and the fiber!). If you can't find frozen artichoke hearts, sub in drained canned artichoke hearts.",
        category: "Food",
    },
    {
        id: 100,
        heading: " Vegan Coconut Chickpea Curry",
        image: "https://www.eatingwell.com/thmb/Ikj4aTJI5p3a1zAaJN_xGuCV5_k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5694953-c059a8745e444fae84d41ad0c3a5474b.jpg",
        description: "To make this 20-minute vegan curry even faster, buy precut veggies from the salad bar at the grocery store. To make it a full, satisfying dinner, serve over cooked brown rice. When shopping for simmer sauce, look for one with 400 mg of sodium or less and check the ingredient list for cream or fish sauce if you want to keep this vegan. If you like a spicy kick, add a few dashes of your favorite hot sauce at the end.",
        category: "Food",
    },
    {
        id: 101,
        heading: "Government imposes import restrictions on laptops, tablets",
        image: "https://static.toiimg.com/thumb/resizemode-4,msid-102383219,imgsize-54934,width-720/102383219.jpg",
        description: "With the aim of giving further impetus to its Made in India initiative, the government of India is making imports of laptops tougher. The Directorate General of Foreign Trade (DGFT) in a notification said that exemption from import licensing is provided for up to 20 items per consignment for R&D, testing, benchmarking and evaluation, repair and return, product development purposes. 'Import of laptops, tablets, all-in-one personal computers, and ultra small form factor computers, servers... is 'restricted' with immediate effect,'' it said.",
        category: "TheLatest",
    },
    {
        id: 102,
        heading: "Bullet Train Project: 1 Dead As Girder Launcher Falls On Workers In Gujarat",
        image: "https://c.ndtvimg.com/2023-08/06t0nud_bullet-train-project-construction-ani_120x90_03_August_23.jpg",
        description: "A lot of app developers — big and small — have expressed their displeasure at Apple charging commission for all transactions done through the App Store. Elon Musk threatened to go to ‘war’ with Apple. However, he then had a meeting with Apple CEO Tim Cook at Apple Park in Cupertino. Now, Musk has once again suggested that he will speak to the Apple CEO. ",
        category: "TheLatest",
    },
    {
        id: 103,
        heading: "‘Swad wahi, soch nayi’: How Rocky Aur Rani Kii Prem Kahaani shows Karan Johar’s evolution as a filmmaker",
        image: "https://images.indianexpress.com/2023/08/karan-johar-.jpg?w=640",
        description: "Rocky Aur Rani Kii Prem Kahaani is a reflection of a lot of things but one that stands out is Karan Johar’s love for cinema; it’s infectious and as his audience, you can’t help but end up with gooey eyes yourself.Karan Johar has a larger-than-life public persona and a maximalist vibe, both of which the filmmaker has worn like a badge over the years. But, when it comes to his films, he has not always been happy when they’re boxed into ‘Brand Johar’.",
        category: "TheLatest",
    },
    {
        id: 104,
        heading: "New powers to Audi’s flagship",
        image: "https://bl-i.thgim.com/public/incoming/4gjc62/article67132313.ece/alternates/LANDSCAPE_1200/IMG_8244.jpg",
        description: "Audi India has had a good run during the last few months and it is finally clawing back some of its lost market share, thanks in part to the deepening portfolio of both its fossil-fuel powered and electric vehicle offerings. An increase in choice offered is always rewarded by the market, and Audi’s e-trons and GTs are now a common sight on our roads. Unlike some of the other luxury brands who have gone with a more unique, easily identifiable design language for their electrics, Audi has chosen to meld its ICE and EV worlds with a design that is more uniform. But its luxe EVs still get a few special features, all within Audi’s trademark focus on minimalist design.",
        category: "LatestArticle",
    },
    ,
    {
        id: 105,
        heading: "IndiGo faces regulatory action after multiple tail strike incidents",
        image: "https://bl-i.thgim.com/public/incoming/z4romm/article67132289.ece/alternates/LANDSCAPE_660/399796289.jpg",
        description: "IndiGo has come under scrutiny following four tail strike incidents on their A321 aircraft within a short span of six months in 2023. In response to these incidents, the Directorate General of Civil Aviation (DGCA), the country’s civil aviation regulator, conducted a special audit of the airline’s operations, raising concerns about its safety procedures.",
        category: "LatestArticle",
    },
    ,
    {
        id: 106,
        heading: "ServiceNow unveils India Innovation Centre",
        image: "https://bl-i.thgim.com/public/incoming/84ydut/article67090269.ece/alternates/LANDSCAPE_660/PO30_Tech.jpg",
        description: "ServiceNow, a digital workflow company, announced the opening of ServiceNow’s new Innovation Centre, a digital incubation hub for Indian enterprises to model, demonstrate, and stress-test digital roadmaps – such as GenAI, hyper-automation, and low code apps - to deliver a better experiences for customers and employees.  ",
        category: "LatestArticle",
    },
    ,
    {
        id: 107,
        heading: "5G deployment. Operators speed up 5G base station rollouts",
        image: "https://bl-i.thgim.com/public/incoming/oeo6d5/article66697508.ece/alternates/LANDSCAPE_660/IMG_2019-04-23T105341Z_1_2_1_KN9U5JHV.jpg",
        description: "Telecom operators have ramped up the deployment of 5G network in March. According to data reported by the Department of Telecommunications- Reliance Jio and Bharti Airtel increased the deployment of 5G BTS by almost 42 per cent between 19 March to 2 April, deploying almost 24,506 BTS. In comparison to this, telcos deployed 13,989 stations between 5 March and 19 March. This is a massive spike in BTS deployment for operators in comparison to previous months.",
        category: "LatestArticle",
    },
    ,
    {
        id: 108,
        heading: "Alia Bhatt shows she can serve effortless glam in streetwear and ethnic fits with two stylish looks.",
        image: "https://www.hindustantimes.com/ht-img/img/2023/08/04/550x309/Alia_Bhatt_1691124229872_1691124240014.jpg",
        description: "Alia Bhatt is a true-blue fashionista with a steal-worthy wardrobe. The star is known for her effortless and minimal sartorial choices, from comfy airport looks to stylish ethnic attires and statement-making red carpet-ready gowns. Most recently, during the promotions of Karan Johar's film Rocky Aur Rani Kii Prem Kahaani, Alia made chiffon sarees the IT look in several beauteous numbers - yesterday, she wore a Rani pink drape to attend an event with Ranveer Singh and Karan Johar. And today, while catching a flight out of Mumbai, she nailed a streetwear look in a chic outfit. Proving that she can easily slay any fashion statement effortlessly.",
        category: "TopPost",
    },
    {
        id: 109,
        heading: "The 'Virat Kohli Factor' Behind Hardik Pandya's Unbeaten 70 In 3rd ODI",
        image: "https://c.ndtvimg.com/2023-08/fcf3d39o_virat-kohli-and-hardik-pandya-bcci_625x300_02_August_23.jpg?im=FaceCrop,algorithm=dnn,width=806,height=605",
        description: "Star all-rounder Hardik Pandya said stalwarts Rohit Sharma and Virat Kohli needed to be rested for the second and third ODIs against West Indies to help India give opportunities to youngsters ahead of the World Cup. Skipper Rohit and former captain Kohli were rested once again in the final ODI of the series, which India won 2-1 after a whopping 200-run victory here on Tuesday under Hardik's leadership.'Virat and Rohit are very integral part of the team. And, you know, obviously, this was very important for someone like Rutu (Ruturaj Gaikwad) to get a game or Axar (Patel) to get a game because they've been playing cricket for so many years, they know how exactly all these situations have been.",
        category: "TopPost",
    },
    {
        id: 110,
        heading: "Highest land price in Hyderabad history at Neopolis Layout Kokapet",
        image: "https://image.telanganatoday.com/wp-content/uploads/2023/08/HMDA_V_jpg--816x480-4g.webp?sw=1280&dsz=816x480&iw=659&p=false&r=1.5",
        description: "Hyderabad: The e-auction of seven prime open plots in Neopolis Layout at Kokapet, spread over 45.33 acres, has garnered huge response from investors, with Hyderabad Metropolitan Development Authority (HMDA) on Thursday generating a record Rs 3,319.6 crore with the highest bid going for an all time high of Rs 100.75 crore for one acre of plot in Telangana. ",
        category: "TopPost",
    }, {
        id: 111,
        heading: "High tomato prices: Punjab governor halts its consumption in Raj Bhawan",
        image: "https://cdn.downtoearth.org.in/library/large/2023-06-30/0.17502300_1688095838_0.jpg",
        description: "As a gesture of solidarity with the citizens facing the impact of high prices of tomato, Punjab governor Banwarilal Purohit on Thursday issued an order temporarily halting its consumption in Raj Bhawan.",
        category: "TopPost",
    },
    {
        id: 112,
        heading: "Pininfarina’s Pura Vision Concept: Sculpting A Glass-Roofed Masterpiece",
        image: "https://www.rushlane.com/wp-content/uploads/2023/08/pininfarina-pura-vision-concept-debuts-2-768x432.jpg",
        description: "Italian car design firm and coachbuilder Pininfarina has unveiled Pura Vision concept in official pictures. This is a baseline on which Pininfarina’s new electric SUV will take shape. The Luxury SUV market is an active space with legacy manufacturers craving for a piece of this pie. Mahindra owned Pininfarina just joined this race.",
        category: "LatestStories",
    }, {
        id: 113,
        heading: "India's Latest Maritime Headache: Cambodia's New China-Built Port",
        image: "https://c.ndtvimg.com/2023-08/tnim52oo_china-cambodia_120x90_05_August_23.jpg",
        description: "China's claims to territory in the South China Sea, its construction of artificial islands in the region, and its establishment of a military base in Djibouti are all evidence of its desire to increase its sphere of influence.",
        category: "LatestStories",
    },
    {
        id: 114,
        heading: "Massive Search On In Kashmir's Kulgam For Terrorists Who Killed 3 Soldiers",
        image: "https://c.ndtvimg.com/2019-09/qhuaa4s4_jammu-and-kashmir-security-afp-_120x90_04_September_19.jpg",
        description: "Security forces launched a massive search operation today to trace a group of terrorists who killed three Army personnel during an encounter a day earlier in Jammu and Kashmir's Kulgam district, officials said.",
        category: "LatestStories",
    },
]
module.exports=dataDummy